# Generated by Django 3.1.7 on 2021-04-07 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Superheros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superhero',
            old_name='runtime',
            new_name='powers',
        ),
        migrations.RemoveField(
            model_name='superhero',
            name='release_date',
        ),
    ]
